### ISSUE TITLE
Conformal mapping plot: right half of z plane to unit disk

### ISSUE THREAD

**Issue by Audrius-St** [eprovst/DomainColoring.jl#12]
Hello,

I'm learning how to use this very useful package to display conformal maps having recently read the wonderful book: Wegert, Elias. _Visual complex functions: an introduction with phase portraits._ Springer Science & Business Media, 2012.

As a test, I tried to plot the following conformal map

![Map 3-19](https://github.com/eprovst/DomainColoring.jl/assets/26634154/a2a56477-dde2-4083-8210-6e29ee8fdfdf)

from Kythe, Prem K. _Handbook of conformal mappings and applications_. CRC Press, 2019.

Using the following code

```
# test_conformal_mapping.jl

using DomainColoring
using GLMakie

function f_z(z::ComplexF64)::ComplexF64
    r, _ = reim(z)
    w::ComplexF64 = 0.0 + im*0.0

    if r >= 0.0
        w = z
    else
        w = NaN + im*NaN
    end

    return w
end

function f_unit_disk(z::ComplexF64)::ComplexF64
    r, _ = reim(z)
    w::ComplexF64 = 0.0 + im*0.0

    if r >= 0.0
        w = (z - 1.0) / (z + 1.0)
    else
        w = NaN + im*NaN
    end

    return w
end

function f_exp(z::ComplexF64)::ComplexF64
    r, _ = reim(z)
    w::ComplexF64 = 0.0 + im*0.0

    if r >= 0.0
        w = exp(z)
    else
        w = NaN + im*NaN
    end

    return w
end

function conformal_map_unit_disk(f_z, f_unit_disk; bounds)
    figure = Figure(fontsize = 32)

    axis_11 = 
        Axis(
                figure[1,1], 
                title=L"z \rightarrow z",
                aspect=DataAspect()
            )
    checkerplot!(axis_11, z -> f_z(z), bounds)

    axis_12 = 
        Axis(
                figure[1,2],
                title=L"z \rightarrow \frac{z - 1}{z + 1}",
                aspect=DataAspect()
            )
    checkerplot!(axis_12, z -> f_unit_disk(z), bounds)

    axis_13 = 
        Axis(
                figure[1,3],
                title=L"z \rightarrow \frac{z - 1}{z + 1}",
                aspect=DataAspect()
            )
    domaincolor!(axis_13, z -> f_unit_disk(z), bounds, abs=true)

    wait(display(figure))
end

function main()
    bounds = (-1.0, 8.0*π, -4.0*π, 4.0*π)
    conformal_map_unit_disk(f_z, f_unit_disk; bounds)
end

begin
    main()
end
```

However, the result is not what I expected.

![Conformal_map_right_z_plane_to_unit_disk](https://github.com/eprovst/DomainColoring.jl/assets/26634154/ec88aea0-ddee-404e-94ca-33076d4a5251)

For example, I would expect the point z = 0 to map to w = -1.

So I'm a bit puzzled. Is there an issue with my above code or in my understanding of conformal maps.

**Comment by eprovst** [comment]
I find the `box` option rather useful to play with conformal maps. Compare for instance
`domaincolor(z->z, 2, box=[(0,10+10im,:blue), (0,10-10im,:red)])`
to
`domaincolor(w->(1+w)/(1-w), 2, box=[(0,10+10im,:blue), (0,10-10im,:red)])`

You see both squares being mapped to the unit circle (of course not the entire ubnit circle is filled as the squares are not infinite). Note the use of the expression for $z$ as a function of $w$. The axes show the input space and the colouring the output space. We want to see where the squares (which live in the $z$-plane) end up in the $w$-plane, hence we want to map the axes to the $w$-plane and the colouring to the $z$-plane.

Plotting conformal maps generally involves the inverse transform, that took me a while to graps 😅 

Hope this helps!

**Comment by eprovst** [comment]
(To see the entire unit circle you can use `domaincolor(w->(1+w)/(1-w), 2, box=[(0,Inf+Inf*im,:blue), (0,Inf-Inf*im,:red)])`)
