### ISSUE TITLE
Feature Request Polar Grids

### ISSUE THREAD

**Issue by KlausC** [eprovst/DomainColoring.jl#9]
Additional to the Cartesian grid, which is enabled by `grid=true` it should be possible to enable grids for lines of
equal angles and lines of equal absolute values.
For example `polargrid=true` could behave like `polargrid=(24, 0.3)`, meaning all angles which are multiples of `(2π / 24)`
and all absolute values which are multiples of `0.3` should be highlighted.

Additional keyword argument `log=true` could be used to refer the grids to `log(abs(z))` instead of `abs(z)`.

**Comment by eprovst** [comment]
For instance, this would be a minimal example of your request:
```julia
using ColorTypes
import DomainColoring as DC

function myshader(w)
    gd = abs(sin(16*angle(w))*sin(5π*log(abs(w))))^0.06
    mapc(c -> gd*c, DC.labsweep(angle(w)))
end

myplot(f, args...; kwargs...) = DC.shadedplot(f, myshader, args...; kwargs...)
```

**Comment by eprovst** [comment]
Since the latest commit, something like `domaincolor(sin, grid=(polar=(7, 10),))` would work.

**Comment by eprovst** [comment]
Most of this request has been included in the latest release, thanks!
